int Nelio ( int );
int Suorakaide ( int, int );
float MatkanHinta ( float, float, float );
int palkka ( int );
void tervehdys();
int summa( int luku1, int luku2 );
float Virta( float, float );
void sulake( double );
void lotto();
void tulostaTahtia( int );
bool alkuluku( int );
void asetaIka( int& );
void arvoLottonumerot( int lotto[] , int );